CREATE TABLE festivo(
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL,
	dia INT NOT NULL,
	mes INT NOT NULL,
	diasPascua INT NOT NULL,
	idTipo BIGINT NOT NULL,
	CONSTRAINT fkFestivo_Tipo FOREIGN KEY (idTipo) REFERENCES tipo(id)
);